CREATE TABLE trees (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    account_id VARCHAR(255) NOT NULL,
    account_hash VARCHAR(64) NOT NULL,
    merkle_root VARCHAR(64) NOT NULL,
    proof_file_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)